# identifiant du projet (clé unique pour SonarQube)
sonar.projectKey=univ:escaladeclub
# nom du projet affiché par l'interface graphique
sonar.projectName=climbingclub
# Version du projet affichée dans l?interface graphique
sonar.projectVersion=${project.version}
# chemin relatif des fichiers sources, par ex . ou src ou liste séparée par ,
sonar.sources=src/main
sonar.tests=src/test
# pour Java, chemin des fichiers compilés .class du projet (par ex. target)
sonar.java.binaries=target/classes
# exclure les fichiers/dossiers non pertinents (par ex **/bin/**)
sonar.exclusions=**/target/**,**/build/**,**/.idea/**,**/bin/**
# encodage des fichiers sources
sonar.sourceEncoding=UTF-8
# URL du serveur SonarQube (ex. http://localhost:9000)
sonar.host.url=http://localhost:9000